### ISSUE TITLE
Elda pages not displaying propertly in IE9

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/sedgemoor-data#11]
The banner at the top of page does not render correctly.

**Comment by ijdickinson** [comment]
Is this the already mentioned IE9 problem, or something else?

**Comment by bwmcbride** [comment]
This is the same one I mentioned in email.  Logged here so I have a view of all Sedgemoor related issues.

**Comment by ijdickinson** [comment]
Created epimorphics/elda#117 for tracking this issue on the Elda project itself.
