### ISSUE TITLE
B-nodes being displayed as live http hyperlinks

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/sedgemoor-data#12]
For example, in a describedBy statement.

**Comment by ijdickinson** [comment]
You don't state whether this is in the Elda output, but if it is it's likely a duplicate of epimorphics/elda#115.

**Comment by bwmcbride** [comment]
Looks like the same problem.  I'll keep this tracker entry so I have a list of issue affecting the Sedgemoor system.
